open System
open Intrinio
open log4net
open log4net.Config
open System.Reflection
open System.IO

type TestProvider() =
    interface IQuoteProvider with
        member this.AuthURL() = "https://superfeed-websocket-lb-be5081c7e7d84436.elb.us-east-1.amazonaws.com/auth"//"http://54.208.142.18:80/auth" //"http://52.22.8.100:80/auth"
        
        member this.MakeWebSocketUrl(token : string) = sprintf "wss://superfeed-websocket-lb-be5081c7e7d84436.elb.us-east-1.amazonaws.com/websocket?token=%s" token //"ws://54.208.142.18:80/websocket?token=%s" 

[<EntryPoint>]
let main argv =
    let logRepository = LogManager.GetRepository(Assembly.GetEntryAssembly())
    XmlConfigurator.Configure(logRepository, FileInfo("IntrinioRealTime.dll.config"))
    let client = Intrinio.RealTimeClient(QuoteProvider.IEX,api_key="OmMwYTZiZWVhZGM3ZGZiMzA5YTEwMTk5OTQ2YzQ2MTll",customProvider=TestProvider())
    
    let handler = QuoteHandler()
    handler.add_OnQuote(fun (quote : IQuote) -> Console.WriteLine(quote.ToString()))
    //handler.add_OnQuote(fun (quote : IQuote) -> Console.Write('.'))
    client.RegisterQuoteHandler(handler)
    client.Connect()
    client.Join("AAPL")
    
    client.Join("ACOR")
    client.Join("ACP^")
    client.Join("ACP^#")
    client.Join("ACP")
    client.Join("ACRE")
    client.Join("ACRS")
    client.Join("ACRX")
    client.Join("ACSF")
    client.Join("ACSG")
    client.Join("ACSI")
    client.Join("ACST")
    client.Join("ACT")
    client.Join("ACTA")
    client.Join("ACTG")
    client.Join("ACTpA")
    client.Join("ACTT")
    client.Join("ACTTU")
    client.Join("ACTTW")
    client.Join("ACTX")
    client.Join("ACU")
    client.Join("ACV")
    client.Join("ACW")
    client.Join("AC/WD")
    client.Join("ACWF")
    client.Join("ACWI")
    client.Join("ACWV")
    client.Join("ACWX")
    client.Join("ACXM")
    client.Join("ACY")
    client.Join("ADAP")
    client.Join("ADBE")
    client.Join("ADC")
    client.Join("ADES")
    client.Join("ADGE")
    client.Join("ADHD")
    client.Join("ADI")
    client.Join("ADIL")
    client.Join("ADILW")
    client.Join("ADK")
    client.Join("ADK-A")
    client.Join("ADM")
    client.Join("ADMA")
    client.Join("ADME")
    client.Join("ADMP")
    client.Join("ADMS")
    client.Join("ADNT")
    client.Join("ADNTw")
    client.Join("ADOM")
    client.Join("ADP")
    client.Join("ADPT")
    client.Join("ADRA")
    client.Join("ADRD")
    client.Join("ADRE")
    client.Join("ADRO")
    client.Join("ADRU")
    client.Join("ADS")
    client.Join("ADSK")
    client.Join("ADSW")
    client.Join("ADT")
    client.Join("ADTN")
    client.Join("ADUS")
    client.Join("ADVM")
    client.Join("ADX")
    client.Join("ADXN")
    client.Join("ADXS")
    client.Join("ADXSW")
    client.Join("ADYX")
    client.Join("ADZ")
    client.Join("AE")
    client.Join("AEB")
    client.Join("AEC")
    client.Join("AED")
    client.Join("AED*")
    client.Join("AEE")
    client.Join("AEF")
    client.Join("AEFC")
    client.Join("AEG")
    client.Join("AEGN")
    client.Join("AEH")
    client.Join("AEH*")
    client.Join("AEHR")
    client.Join("AEIS")
    client.Join("AEK")
    client.Join("AEK*")
    client.Join("AEL")
    client.Join("AEL-A")
    client.Join("AEM")
    client.Join("AEMD")
    client.Join("AEO")
    client.Join("AEP")
    client.Join("AEP-B")
    client.Join("AER")
    client.Join("AERI")
    client.Join("AES")
    client.Join("AES-C")
    client.Join("AES-C*")
    client.Join("AESE")
    client.Join("AESEW")
//    client.Join("AESpC")
//    client.Join("AESR")
//    client.Join("AET")
//    client.Join("AETI")
//    client.Join("AEUA")
//    client.Join("AEY")
//    client.Join("AEYE")
//    client.Join("AEZS")
//    client.Join("AF")
//    client.Join("AFA")    
    //client.Join("$lobby")
    
    
    
    Console.ReadLine()
    0 // return an integer exit code
